name: Deploy
on:
  push:
    branches:
      - feat-2
permissions:
  contents: read
jobs:
 gh-pages-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout branch
     uses: actions/checkout@v2
   - name: Setup Node.js for use with actions
     uses: actions/setup-node@v2
     with:
      version: 18
   - name: Clean install dependencies
     run: npm ci
   - name: Deploy with gh-pages
     env:
      MY_EMAIL: yagellonikita94@gmail.com
      MY_NAME: NikitaYagello
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: |npx semantic-release

     
